WEB3-323: fix: use rzup (#421)
Installs the rust toolchain using rzup.

this fixes the following error we are currently seeing in the CI:
```
cargo risczero install --version r0.1.81.0
Error: Run `rzup install` instead
```

This PR also contains #424  which is necessary to make the tests pass.

---------

Co-authored-by: Victor Snyder-Graf <victor@risczero.com>